### ISSUE TITLE
ping() does not work in Docker image

### ISSUE THREAD

**Issue by hjacobs** [zalando-zmon/zmon-worker#116]
> der Check-Command ping() liefert mir ein "[Errno 2] No such file or directory"
in unseren System aber auch unter demo.zmon.io.

> Aktuell habe ich nur einen Ping-Check mit folgenden Inhalt:
> ping()

**Comment by hjacobs** [comment]
hmm, yes, ping is not part of the Docker image, but it's invoked here: https://github.com/zalando-zmon/zmon-worker/blob/master/zmon_worker_monitor/builtins/plugins/ping_.py#L30

**Comment by mohabusama** [comment]
Resolved by 74c0ea4d7874c0bfd162fae6ea393c3053fa978e
