### ISSUE TITLE
support CNAME lookups

### ISSUE THREAD

**Issue by femueller** [zalando-zmon/zmon-worker#119]
Please add the support for local execution of the check_dig nagios plugin.

**Comment by hjacobs** [comment]
Probably we should rephrase/rename this issue to "support CNAME lookups" or similar.

**Comment by femueller** [comment]
@hjacobs done

**Comment by femueller** [comment]
https://github.com/zalando-zmon/zmon-worker/pull/211 will fix this issue.

**Comment by femueller** [comment]
This can be closed since #211 is merged.
