### ISSUE TITLE
Add ability to specify oauth2 scopes for http checks

### ISSUE THREAD

**Issue by whiter4bbit** [zalando-zmon/zmon-worker#155]
Currently, access token is requested just for 'uid' scope. But some endpoints require specific scopes. 

It is possible to read scopes from env var:

```
ZMON_WORKER_OAUTH2_TOKENS=token_name1=scope1,scope2,scope3:token_name2=scope1,scope2
```

and add `token_name` argument  `http`:

```
http('http://example.com', oauth2=True, token_name='token_name1')
```

for backward compatibility use 'uid' as default token name

**Comment by mohabusama** [comment]
This could be somehow related to #132 in a more generic way.

**Comment by whiskeysierra** [comment]
I'd like to prepare a pull request for this. Just to clarify, because I don't know the architecture of ZMON too well: The worker is traditionally running as an appliance in individual AWS accounts, so with this in place I could basically assign the correct scopes to our ZMON application that's it?

**Comment by whiskeysierra** [comment]
I'd suggest to use `ZMON_WORKER_WORKER_PLUGIN_HTTP_OAUTH2_TOKENS` so we can configure the HTTP plugin with `conf.get('oauth2.tokens')`. Thoughts?

**Comment by whiskeysierra** [comment]
Ah, I just realized the tokens library is configured outside the class... 

https://github.com/zalando-zmon/zmon-worker/blob/master/zmon_worker_monitor/builtins/plugins/http.py#L23

**Comment by Jan-M** [comment]
You can use the http plugin factory maybe to inject the tokens you configured more nicely.

**Comment by whiskeysierra** [comment]
Like this?

```python
class HttpFactory(IFunctionFactoryPlugin):
    def __init__(self):
        super(HttpFactory, self).__init__()

    def configure(self, conf):
        """
        Called after plugin is loaded to pass the [configuration] section in their plugin info file
        :param conf: configuration dictionary
        """
        # will use OAUTH2_ACCESS_TOKEN_URL environment variable by default
        # will try to read application credentials from CREDENTIALS_DIR
        tokens.configure()
        tokens.manage('uid', ['uid'])

        # ZMON_WORKER_WORKER_PLUGIN_HTTP_OAUTH2_TOKENS
        token_configuration = conf.get('oauth2.tokens')

        if token_configuration:
            for part in token_configuration.split(':'):
                token_name, scopes = tuple(part.split('=', 1))
                tokens.manage(token_name, scopes.split(','))

        tokens.start()
```

**Comment by Jan-M** [comment]
Yes that's pretty much it.
