### ISSUE TITLE
Allow configuring oauth scopes

### ISSUE THREAD

**Issue by marek-obuchowicz** [zalando-zmon/zmon-worker#182]
At the moment oauth scope for token requests is hardcoded to `uid` in https://github.com/zalando-zmon/zmon-worker/blob/master/zmon_worker_monitor/zmon_worker/tasks/main.py#L734

Please allow configuration of other scopes via environmental variables.

**Comment by Jan-M** [comment]
You want to do this add e.g. a data.write scope for writing to data-service?

Sounds reasonable, but we should maybe also look at all other places. E.g kairosdb and history query data service.

**Comment by vetinari** [comment]
see #155
