### ISSUE TITLE
Mathematical functions missing from the default context

### ISSUE THREAD

**Issue by mtesseract** [zalando-zmon/zmon-worker#196]
Hi,

in one of our ZMon alerts we would like to use some functions contained in the python package "math"; background being here that we would like to use a function for recognizing "unusual behaviour" of some of our metrics. This function makes use of the logarithmic function math.log10.

To allow this, it would be great if we could bring the whole math package into scope?

Thanks,
Moritz

**Comment by mohabusama** [comment]
Closed via #197
