### ISSUE TITLE
Kubernetes Wrapper

### ISSUE THREAD

**Issue by hjacobs** [zalando-zmon/zmon-worker#203]
As ZMON now runs within Kubernetes clusters, we need some easy-to-use Kubernetes wrapper to be used in ZMON check definitions. Example:

```python
# return number of ready pods for "myapp"
def check():
   pods = kubernetes().pods(application="myapp")
   return len([pod for pod in pods if pod['ready']])
```

The concrete API should be drafted/discussed before implementing.

**Comment by mohabusama** [comment]
Initial proposal

## Kubernetes Wrapper

### kubernetes

We will be dependent on ``serviceaccount`` for authentication (used by ``pykube``)

```python
kubernetes(namespace='default')
```

### Pods

Pykube/Kubernetes allows filtering on both:

- labelSelector
- fieldSelector (not very clear https://github.com/kubernetes/kubernetes/issues/15128)

``labelSelector`` is flexible and would help in certain useful scenarios, e.g.:

- application in ('app-1', 'app-2')
- appliacation notin ('app-2', 'app-3')

Pykube supports label and field selectors, however ``fieldSelector`` are not as flexible. Suggestion is to hide ``fieldSelector`` and expose only useful ones:

- phase
- ready

We can also expose certain useful labels (and by useful it might not fit into the OSS nature of ZMON)

- application
- version

however, we will need to expose the flexibility of labelSelector (e.g. ``application__in=['app-1', 'app-2'] should be supported!

Or, we can just support ``labels={'application__in'=['app-1', 'app-2']}``

```python
kubernetes().pods(name='pod-1')

kubernetes().pods(application__neq='app-1', version='v1.1', phase='Running')
kubernetes().pods(application__notin=['app-1', 'app-2'], phase='Running')
kubernetes().pods(application='app-1', ready=True, labels={'custom-label__in': ['c1', 'c2']})

# OR only via *labels*
kubernetes().pods(ready=True, labels={'application__in': ['app-1', 'app-2'], 'version': 'v1.1'})
```

### Nodes

Nodes could also use ``labelSelector`` but not clear if some labels need exposing.

```python
kubernetes().nodes(labels={'beta.kubernetes.io/os': 'linux'})
kubernetes().nodes(name='ip-192.168.20.17-cential')
```

### More Workload Resources

Following resources are roughly similar to Pods:

- ReplicaSet
- Deployment
- StatefulSet

### Config Resources

**Q** Do we need to include config resources?

- ConfigMap
- PersistentVolumeClaim
- PersistentVolume

### LoadBalancing Resources

- Service
- Endpoints
- Ingress

**Comment by mikkeloscar** [comment]
> `kubernetes(namespace='default')`

I assume it works by default, but to make sure, we should also be able to do `namespace='all'`.

> however, we will need to expose the flexibility of labelSelector (e.g. application__in=['app-1', 'app-2'] should be supported!)

I like that the labels are 'first class'. This is similar to the labels exposed as entities which is really helpful.

> ### Config Resources
>
> **Q** Do we need to include config resources?
>
> ConfigMap
> PersistentVolumeClaim
> PersistentVolume
> 
> ### LoadBalancing Resources
>
> Service
> Endpoints
> Ingress

I think it should be possible to query all parts of the Kubernetes API through ZMON (apart from secrets). But I'm not sure if we really need this nice wrapper for all resources.

For cluster level checks we need access e.g. to `/metrcis` of the API server, but for me it would be fine if this was exposed through something like `kubernetes().http("/custom/query").json()` so you don't need to create a wrapper for every possible resource which is only used in a few checks.

**Comment by linki** [comment]
> kubernetes().pods(application__neq='app-1', ... )

We could also go with a less structured approach if possible:

```python
kubernetes().pods(labels="app=mate,stage!=production,chaos") # last one means "it's set to any value"
```

The go client supports parsing and filtering by this out of the box, maybe `pykube` does as well.

**Comment by linki** [comment]
Since `application` and `version` are "standardized" by us and will be used a lot it might make sense to promote them to functions, e.g.

```python
kubernetes().application('app-1').version('1.1').pods(phase='Running')
```

Would also allow to seamlessly find other related resources:

```python
my_app = kubernetes().application('app-1').version('1.1')
my_pods = my_app.pods(phase='Running')
my_services = my_app.services()
```

**Comment by mohabusama** [comment]
Thanks @mikkeloscar @linki for the feedback!

> we should also be able to do namespace='all'

Good point. I feel ``all`` might conflict with a valid namespace.
Possible solutions:

```python
kubernetes()  # default namespace
kubernetes(namespace=None)  # All namespaces

# or use specific not very common value
kubernetes(namespace='*')  # All namespaces
```

In either cases, we need to make querying **all** namespaces explicit, otherwise we might end up with excessive unnecessary number of calls to API server.

> we need access e.g. to /metrcis of the API server

Is ``/metrics`` pointing to a Kubernetes resource or something custom? I feel the normal HTTP wrapper can suffice in this case (with appropriate entity filtering in the check or alert). If it is a Kubernetes resource then we can expose it as ``kubernetes().metrics()``.

> We could also go with a less structured approach if possible:
kubernetes().pods(labels="app=mate,stage!=production,chaos")

Pykube doesn't support this syntax, although it ends up with something similar in the API call. We could add a parser that converts this syntax to pykube one. FWIW Pykube uses a more Pythonic and commonly used style for filtering (fi ORM style). It also helps in extending the syntax with client-level filtering (e.g. ``application__startswith='zmon-'`` or ``application__endswith='-worker'`` etc ...)

> Since application and version are "standardized" by us and will be used a lot it might make sense to promote them to functions, e.g.
kubernetes().application('app-1').version('1.1').pods(phase='Running')

As you mentioned, ``application`` and ``version`` are not Kubernetes standard, it is only required by Z. imho in an OS context, it won't help and the interface would be confusing.

**Comment by mikkeloscar** [comment]
> Is /metrics pointing to a Kubernetes resource or something custom? I feel the normal HTTP wrapper can suffice in this case (with appropriate entity filtering in the check or alert). If it is a Kubernetes resource then we can expose it as kubernetes().metrics().

It's the `/metrics` endpoint of the API server and just an example. There might be other resources which we want to query which are not part of the Kubernetes wrapper interface for ZMON.
The only reason we can't do plain `http()` is that ZMON can't authenticate with the API server right now.
