### ISSUE TITLE
Add proper User-Agent to identify ZMON worker versions

### ISSUE THREAD

**Issue by hjacobs** [zalando-zmon/zmon-worker#21]
The HTTP wrapper and other HTTP requests should set a proper User-Agent HTTP header

**Comment by hjacobs** [comment]
Still to do:

* set User-Agent for all HTTP requests to ZMON Controller / Data Service
* set User-Agent for all HTTP requests to ZMON Metric Cache and KairosDB
* maybe other places?

**Comment by beverage** [comment]
@hjacobs @mohabusama Were the todos above ever done?
