### ISSUE TITLE
Support Basic-Auth credentials for http wrapper

### ISSUE THREAD

**Issue by Jan-M** [zalando-zmon/zmon-worker#215]
While netrc config file does work to set credentials another idea would be to specify basic auth credential pairs via env variable and allow user in check to write something like ```http(user='xyz')``` and let the worker pick up the credentials and use them.

**Comment by beverage** [comment]
@vetinari @mohabusama @Jan-M Do we still want this?  I see the PR was stalled long ago: https://github.com/zalando-zmon/zmon-worker/pull/295
