### ISSUE TITLE
Support for CloudWatch put-metric-data

### ISSUE THREAD

**Issue by imduffy15** [zalando-zmon/zmon-worker#243]
When using AWS CloudWatch put-metric-data their is no flexibility to modify the data before storing.

ZMON is different, we can poll a http endpoint on a given interval and execute calculations on it and what not before returning a value.

However, by using ZMON for monitoring it means I'm unable to do some of the neat features that come with CloudWatch Metrics (e.g. autoscale).

It would be neat if I could call put-metric-data from a ZMON check to make this data available in the AWS world.

Would love to hear thoughts on how this should be exposed and will open the PR necessary to get it done.

**Comment by hjacobs** [comment]
Hmm, I'm not sure if I'm in favor of the idea of letting ZMON push data to CloudWatch. If we want something like this, it should IMHO be decoupled and something like "read data from ZMON/KairosDB and push to CloudWatch" bridge.

**Comment by imduffy15** [comment]
> Hmm, I'm not sure if I'm in favor of the idea of letting ZMON push data to CloudWatch
That's OK was aiming for a method that was easy and give a very quick win.

> it should IMHO be decoupled and something like "read data from ZMON/KairosDB and push to CloudWatch" bridge.

How would you see this being implemented? Another docker container running on the ZMON appliance? check box to enable a check to be bridged?

**Comment by beverage** [comment]
Closing as a solution to this problem would not be a ZMON feature but a new product.
