### ISSUE TITLE
Make connect_timeout configurable for PostgreSQL

### ISSUE THREAD

**Issue by alexeyklyukin** [zalando-zmon/zmon-worker#245]
Right now, the worker hard-codes it to 5s, which might be not enough in some cases (i.e. loaded databases), leading to false positives that are hard to alleviate. Given that this value is supported by [libpq connection parameters](https://www.postgresql.org/docs/current/static/libpq-connect.html#LIBPQ-PARAMKEYWORDS) it is quite easy to make it configurable.

**Comment by mohabusama** [comment]
Fixed by #244
