### ISSUE TITLE
Alert tags are not sent to OPSgenie

### ISSUE THREAD

**Issue by tuxlife** [zalando-zmon/zmon-worker#249]
We as OPSgenie user want use the alert tags from zmon to filter the alert in opsgenie.

But currently, the zmon-worker doesn't know anything about the tags and can't send this to opsgenie.

**Comment by vetinari** [comment]
fixed by  https://github.com/zalando-zmon/zmon-scheduler/pull/74 (and additionally https://github.com/zalando-incubator/kubernetes-on-aws/pull/539)
