### ISSUE TITLE
Fix flaky unit test

### ISSUE THREAD

**Issue by hjacobs** [zalando-zmon/zmon-worker#26]
The main worker test (using multiple processes) sometimes fails:

```
        for string in expected_strings:
>           assert string in data['zmon:checks:123:77']
E           TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by alfre2v** [comment]
This commit might make it go away: https://github.com/zalando/zmon-worker/commit/76566537fd8a5e2f526ac9aa8d0f58176bf5ac49

**Comment by mohabusama** [comment]
@hjacobs I believe we can close this one?

**Comment by hjacobs** [comment]
Yes, looks fine now.
