### ISSUE TITLE
Report missing plugin configurations properly (e.g. WORKER_PLUGIN_SCALYR_READ_KEY)

### ISSUE THREAD

**Issue by amjedonline** [zalando-zmon/zmon-worker#27]
Zmon worker returns an error on trying to get timeseries based logs from scalyr
Here is a simple 
**check definition**
`def check():
    query = "$serverHost='my-awesome-service' $severity >= '5'"
    return scalyr().timeseries(query, minutes=5)`

**Results in**
`{"status":"error/client/badRequest","message":"request must have 'token' field"}`

**Comment by hjacobs** [comment]
@amjedonline you need to set the environment variable `WORKER_PLUGIN_SCALYR_READ_KEY` in your ZMON Worker (https://docs.zmon.io/en/latest/installation/configuration.html#worker).

**Comment by Jan-M** [comment]
You need to specify:
WORKER_PLUGIN_SCALYR_READ_KEY: ....

**Comment by hjacobs** [comment]
We should add a proper error message and unit test for it :smile:

**Comment by Jan-M** [comment]
True ;-)

**Comment by Jan-M** [comment]
Just needs to be checked in the functions and not during partial construction, as it is optional.

**Comment by hjacobs** [comment]
:+1:
