### ISSUE TITLE
Check failing to be executed because zmon-worker can't get an OAuth2 token

### ISSUE THREAD

**Issue by Raffo** [zalando-zmon/zmon-worker#270]
In our ZMON installation (see [Zalando's Kubernetes on AWS setup](https://github.com/zalando-incubator/kubernetes-on-aws) ) we sometimes have checks that fail to run because of no OAuth credentials: 

<img width="719" alt="screen shot 2017-09-21 at 13 49 29" src="https://user-images.githubusercontent.com/683988/30694312-b81312b2-9ed3-11e7-8918-60d376f5cfae.png">

This is due to the fact that `gerry` is not running due to a race condition with [kube2iam](https://github.com/jtblin/kube2iam). Even if this could happen for a short amount of time, we should not rely on the user knowing this transient problem as this will leak infrastructural details of how ZMON works into the check writer. 
Moreover, in this particular case, our check didn't need any OAuth2, but was only using the `http` function (or wrapper? what's the difference?) which should have OAuth2 set to false, even though the [documentation](https://docs.zmon.io/en/latest/user/check-ref/http_wrapper.html) is not really explicit about the default value. 

One possible solution would be to find a way not to fail on missing credentials for check that do not require credentials. 

I would also consider investigating a way to determine if zmon worker is able to work correctly before failing on user checks: in this case what is really failing is the zmon-worker component due to a missing dependency and this should probably not trigger alerting/paging for the users of ZMON.

**Comment by hjacobs** [comment]
Low hanging fruit: I would do some "active wait" (maybe even just via bash) in our ZMON worker container to wait for credential distribution before starting the ZMON worker Python process.

**Comment by linki** [comment]
A possible fix we could apply immediately: https://github.com/zalando-incubator/kubernetes-on-aws/pull/790

**Comment by beverage** [comment]
Fixed per https://github.com/zalando-incubator/kubernetes-on-aws/pull/790
