### ISSUE TITLE
CloudWatch alarm should have optional state_value parameter

### ISSUE THREAD

**Issue by musiKk** [zalando-zmon/zmon-worker#272]
Right now the `state_value` for `cloudwatch().alarms()` either has to be provided or defaults to `ALARM` if omitted. While this is a sensible default I would find it very useful to be able to set this to `None` in order to omit it from the underlying query entirely. That way I could do the evaluation in the ZMON alert and validate that the alarm is actually present. This way I would not have a false sense of security if I check for a concrete alarm that got removed and therefore never triggers the ZMON alert. To date this can only be accomplished by making two separate calls for `alarm_state`s `OK` and `ALARM` (or even three if I also want to check for `INSUFFICIENT_DATA`).

**Comment by hjacobs** [comment]
Sounds reasonable.
