### ISSUE TITLE
Capture time() result fails

### ISSUE THREAD

**Issue by mohabusama** [zalando-zmon/zmon-worker#284]
Returns weird result in Trial Runs

```python
t = time('2017-11-20T17:02:02.000')
capture(tt=t)   # <--
```

![weird result](https://user-images.githubusercontent.com/488406/33032289-075135b2-ce21-11e7-92f8-a2fdc08e35a7.png)

Most probably this is related to JSON data serialization, but not entirely sure.

**Comment by vetinari** [comment]
`capture(tt=t.isoformat())`   works

**Comment by mohabusama** [comment]
True. It is not verbose enough to point to the error tho. So basically this could happen to any non-json-serializable objects. In the check results, we raise proper exception hinting at the fix.

side note: ``time()`` with invalid time spec should raise an error rather than silently setting ``.time`` to ``None``.

**Comment by vetinari** [comment]
fixed by #293?
