### ISSUE TITLE
Consider moving SNMP and Nagios plugins to "extra" plugins

### ISSUE THREAD

**Issue by hjacobs** [zalando-zmon/zmon-worker#29]
I think we should have a clean set of "core" plugins which are 100% supported and unit tested:

* HTTP
* Time
* ZMON
* PostgreSQL
* ..

Some plugins such as SNMP and Nagios are currently not very useful and should move to a new "extra" plugin section. The "extra" plugins should be located in the same git repo, but they should only be loaded on-demand by setting an environment variable.

Benefits:

* Clean separation of 100% supported plugins and "legacy" stuff
* We can exclude the "extra" plugins from code coverage as we will probably never write a full test suite for them
* Startup and test time is faster as less code is loaded

**Comment by hjacobs** [comment]
@Jan-M what do you think?

**Comment by hjacobs** [comment]
This feature would make good use of our plugin infrastructure for the first time :smile:

**Comment by Jan-M** [comment]
My only problem with this is, we cannot advertise to replace Icinga2/Nagios and at the same time remove snmp() and nrpe(), so maybe we can find a base set of functions that would work/make sense.

Otherwise I am fine with "extras", we could even auto build 2 images i guess.

**Comment by hjacobs** [comment]
@Jan-M I would still keep one Docker image for now, just not load the code --- probably we should have a look at a simple ZMON Nagios/Icinga plugin to support the generic Nagios/Icinga plugin protocol (http://docs.icinga.org/latest/de/plugins.html).

Our current ZMON Nagios plugin has too much special logic for our use cases (and probably many Nagios/NRPE plugins we used are outdated).

**Comment by Jan-M** [comment]
:+1 then from my side
