### ISSUE TITLE
Cassandra wrapper: possible connection leak

### ISSUE THREAD

**Issue by mohabusama** [zalando-zmon/zmon-worker#306]
Calling ``cassandra().execute(...)`` **may be** causing connection leak.

- We may need to revisit connection re-usability among several statements: move session initialization to ``__init__``  and use in ``execute``
- Reproduce connection leak

Note: ``cl.shutdown()`` is explicitly called in ``execute()``

**Comment by vetinari** [comment]
Was able to reproduce with cassandra:latest docker image and `cassandra-driver==3.6.0` (ipython using
`Python 2.7.6 (default, Nov 23 2017, 15:49:48)` )
```python
for i in range(1000):
    cl = Cluster(['172.17.0.2'], port=9042)
    sess = cl.connect()
    sess.execute(' select * from system_auth.roles;')
    cl.shutdown()
```
after this loop there's still one connection open:
```
ipython 15330 hhecker    7u  IPv4 687838      0t0      TCP 172.17.0.1:45001->172.17.0.2:9042 (ESTABLISHED)
```

**Comment by vetinari** [comment]
the open connection was not reproducible with `cassandra-driver==3.12.0` - see also https://datastax-oss.atlassian.net/browse/PYTHON-814 - this one opens just one connection, not two like 3.6.0 -> suggestion is to also upgrade the cassandra-driver version
