### ISSUE TITLE
Check that the return type of alert() is a boolean

### ISSUE THREAD

**Issue by ovolynets** [zalando-zmon/zmon-worker#340]
I noticed that some check do not do their job if the return value of the `alert()` function was not a boolean, e.g.:

```
def alert():
    rps = value['some_url']['requests_per_sec']
    capture(rps=rps) < 0.005
```

which does evaluate the capture and the comparison but does not return the `boolean` value required to trigger the check. The right function should look like

```
def alert():
    rps = value['some_url']['requests_per_sec']
    return capture(rps=rps) < 0.005
```
When using the simple syntax for the alert (i.e. skipping `def alert()`), this would work just fine:
```
capture(rps=value['some_url']['requests_per_sec']) < 0.005
```
therefore it is also tricky when extending simple checks: it is easy to forget about the return.
It would be nice to return an error if the type of the returned value is `None`

**Comment by hjacobs** [comment]
@ovolynets thanks for reporting! I think it's just a matter of changing the type conversion and explicitly disallow `None` (`bool(None)` evaluates to `False`): https://github.com/zalando-zmon/zmon-worker/blob/master/zmon_worker_monitor/zmon_worker/tasks/main.py#L1439
