### ISSUE TITLE
http wrapper headers does not return any values

### ISSUE THREAD

**Issue by mohabusama** [zalando-zmon/zmon-worker#341]
In Trial run:

```python
http('https://www.google.com').headers()
```
Expected:

Dict of headers

Actual:

![trial run http](https://user-images.githubusercontent.com/488406/41048173-7383076e-69ae-11e8-8c4e-65d6f51643d2.png)

**Comment by vetinari** [comment]
same for `cookies()`

`text()`, `code()`, `content_size()`, `time()` are ok

**Comment by vetinari** [comment]
wonder if this is related to the `opentracing_utils`, the request seems to be fine in the trace view.

**Comment by rajatparida86** [comment]
closing as already implemented
