### ISSUE TITLE
extend Notifications to Google Chat

### ISSUE THREAD

**Issue by drummerwolli** [zalando-zmon/zmon-worker#350]
Google Chat should get supported by ZMON notifications since its adoption is rising constantly.

**Comment by drummerwolli** [comment]
https://developers.google.com/hangouts/chat/how-tos/webhooks
https://developers.google.com/hangouts/chat/quickstart/incoming-bot-python

might be easily done. i can maybe take a look the next days, but feel free to pursue this earlier ...

**Comment by larminen** [comment]
notify_http should in theory be sufficient to use webhooks. however the JSON body of the POST message is hardcoded to use certain keys that don't match the [expected](https://developers.google.com/hangouts/chat/reference/message-formats/basic)  format from google chat. easy way would be to just make the notify_http body to not have hardcoded keys like 'body' and have user to able to define it.

**Comment by mohabusama** [comment]
Resolved by #360 #363
