### ISSUE TITLE
Revalidate and avoid adding zmon-worker id tag to the check results

### ISSUE THREAD

**Issue by vibhory2j** [zalando-zmon/zmon-worker#355]
Based on internal discussions it has been observed that the tag worker-id is not used by majority of users to query and/or filter the datapoints results. This can potentially reduce the cardinality of tags produced by checks and would result in better stability of timeseries storage. Hence it makes sense to investigate and avoid adding the worker-id tag to the check results.

**Comment by vetinari** [comment]
@vibhory2j this is needed in case we have multiple workers like in k8s where one might error while all others work fine. Without this, you'd never find out.

**Comment by vetinari** [comment]
filter in kairosdb instead
