### ISSUE TITLE
Check whether broken alert notifications prevents alert to pop up

### ISSUE THREAD

**Issue by hjacobs** [zalando-zmon/zmon-worker#37]
To be checked: broken notification settings (e.g. invalid syntax in https://docs.zmon.io/en/latest/user/alert-definitions.html#notifications) should not prevent the alert from popping up (e.g. on the dashboard).

**Comment by mohabusama** [comment]
I tested raising exception deliberately in `send_notification`, this did not prevent alerts from pop-up in dashboard. 
Mainly an exception is logged:

https://github.com/zalando-zmon/zmon-worker/blob/master/zmon_worker_monitor/zmon_worker/tasks/main.py#L1574

@hjacobs, Is there any other scenario to be covered?

**Comment by hjacobs** [comment]
I think that's fine, let's close this.
