### ISSUE TITLE
google chat notifications thread behaviour should be configurable

### ISSUE THREAD

**Issue by drummerwolli** [zalando-zmon/zmon-worker#374]
google chat notifications are allowing threaded messages. currently we thread per alert, but users might prefer different threading styles.

i can think right now of the following possibilities as a value for a upcoming `thread_style` param:
- `alert`: the current behaviour, adding new messages to a thread only containing this alert. i would keep this as default for now.
- `none`: threading feature is not used at all and messages are send to one big thread of zmon alone

there are probably other modes possible, feel free to add ideas.

i can work on the first implementation this afternoon.

**Comment by JonSingh** [comment]
@laceyallyn @mohabusama any thoughts on this? Is there any more information we need or direction?

**Comment by alterrebe** [comment]
Personally I'm fine with the current behavior, but won't object for the thread style customization.

**Comment by laceyallyn** [comment]
@drummerwolli , can you give me some context of what you experienced / why you would want notifications being sent to a "ZMON" thread instead of threading per alert?

What are the limitations of the current implementation and what benefits would the suggested implementation have for your ability to respond to alerts from ZMON?

**Comment by drummerwolli** [comment]
@laceyallyn to be honest: it's subjective. I personally don't have that much of a problem with the current style, but I observed in my team a lack of overview in regards to those notifications, hence I wanted to try a different approach in how these notifications are delivered. If this would help is an open question again.

I don't feel strongly about this topic, I was just was wondering what others feel about this, and offer to implement it, since its a quick win. but if really no one needs it, then we can skip it. I will point my team to this thread additionally to also give feedback.

**Comment by laceyallyn** [comment]
@drummerwolli That's super interesting feedback. 
Definitely have your team add feedback about any limitations they experience with the current way notifications work. If they can really clearly describe the _problems_ they currently have, then we can validate if this is a solution that would have a positive effect  =)

At the moment, we're pretty focused on stuff that will prepare/stabilize ZMON for BlackFriday, so we're being a little more careful about changing stuff that could affect incident response.

**Comment by edchapel** [comment]
I joined a new room where our alerts are reported. A few alerts were historically flaky and resulted in many alerts per day. The result is a room with many hundreds of alerts per thread going back 4+ months. This makes Chat (both desktop app and web) EXTREMELY slow to load all the messages. We are removing the chat notifications from our alerts for this reason.

Alternatives to the default threading configuration could be:
* No threading.
* Thread by UTC date.
* Thread by alert event. For example, alert start until alert end.
* Thread by some content in the alert.

Happy to share more details if you are interested.
