### ISSUE TITLE
Allow authentication to be passwd to redis plugin

### ISSUE THREAD

**Issue by vetinari** [zalando-zmon/zmon-worker#385]
According to the docs https://docs.zmon.io/en/latest/user/check-ref/redis_wrapper.html
And source code https://github.com/zalando-zmon/zmon-worker/blob/master/zmon_worker_monitor/builtins/plugins/redis_wrapper.py#L68
There is no way to pass the authentication in Redis.

**Comment by laceyallyn** [comment]
@osakharchuk I'm assuming by this statement you are suggesting that allowing allowing authentication to be passed in Redis? 

Can you **please confirm** that was your intention, and if that is the case, can you tell me **why** you're requesting this enhancement and **what impact** it will have for you or your work? If you can _express the impact as a number,_ that will be most helpful.
