### ISSUE TITLE
http() check should support method POST

### ISSUE THREAD

**Issue by pitr** [zalando-zmon/zmon-worker#396]
In order to get total number of consumed event we need to do a Post call to Nakadi API
https://nakadi.io/manual.html#/event-types/name/cursor-distances_post

Internal ref:564

**Comment by vetinari** [comment]
There's a pull request already to fix this specific issue: https://github.com/zalando-zmon/zmon-worker/pull/375 - generic POST will probably not be allowed

**Comment by hjacobs** [comment]
`POST` and `PUT` should probably not be allowed as they indicate changing state/data --- ZMON is a monitoring system and should have read-only access.

**Comment by mohabusama** [comment]
The proper way to proceed is to finalize the PR #375 with a `nakadi` wrapper support. Closing.
