### ISSUE TITLE
CloudWatch plugin should also provide Alarm 'metrics'

### ISSUE THREAD

**Issue by sarnowski** [zalando-zmon/zmon-worker#40]
In order to reuse CloudWatch Alarms on my ZMON dashboard, I would like to be able to write checks, that fetch the Alarm State of CloudWatch Alarms:

http://boto3.readthedocs.io/en/latest/reference/services/cloudwatch.html#CloudWatch.Client.describe_alarms

**Comment by hjacobs** [comment]
Sounds like a good idea :smile:
