### ISSUE TITLE
Capture is not working correctly for HipChat notifications.

### ISSUE THREAD

**Issue by tkrop** [zalando-zmon/zmon-worker#78]
It seem as the {{}}-pattern substitution for capture is not working for HipChat notifications, if the message is given explicitly. E.g. in XXX is producing the first line produces

ALERT ENDED: Balance AWS: Business Partner Service Not Found Responses in Last Hour ({details}) on ad-app-tier-business-xxx-service-test-463[aws:xxx:eu-central-1]

instead of 

ALERT ENDED: Balance AWS: Business Partner Service Not Found Responses in Last Hour ({details}) on ad-app-tier-business-xxx-service-481[aws:xxx:eu-central-1]

**Comment by hjacobs** [comment]
@tkrop please never expose Zalando internal information in public GitHub issues. Thanks.
